<?php
    //remove_theme_mods();
    /**
     *  We strongly recommend you do not edit this file or any other files
     *  because at the next update you will lose all your customizations.
     *
     *  If you want to customize theme you can use a child theme or a plugin
     *  extension. For more details about please read the file instructions.txt
     */

    require_once get_template_directory() . '/lib/main.php';
?>
